sudo: required

language: swift

services:
- docker

before_install:
- docker pull swift

script:
- docker run --rm -v $(pwd):/app -w /app swift bash -c "swift build"
- docker run --rm -v $(pwd):/app -w /app swift bash -c "swift test"
